////////////////////////////////////////////////////////////////////////////////////
// Merlin API for Albion Online v1.0.327.94396-live
////////////////////////////////////////////////////////////////////////////////////
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Merlin.API.Direct
{
    /* Internal type: Albion.GameData.CharacterSpellSlot */
    public enum CharacterSpellSlot : short
    {
        MainHand1,
        MainHand2,
        OffHandOrMainHand3,
        Armor,
        Head,
        Shoes,
        Potion,
        Food,
        Mount,
        EscapeDungeon,
        ChangePvpStance,
        CoupDeGrace,
        TotalEntries,
        VisibleEntries = 9,
        ItemEntries = 8,
        Invalid = -1
    }
}
